/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagarTokenRouteImport } from './routes/pagar.$token'
import { Route as EntrarTokenRouteImport } from './routes/entrar.$token'
import { Route as ApiChargesRouteImport } from './routes/api/charges'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedMinhasPeladasRouteImport } from './routes/_authenticated/minhas-peladas'
import { Route as AuthenticatedMinhasCobrancasRouteImport } from './routes/_authenticated/minhas-cobrancas'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedGruposIndexRouteImport } from './routes/_authenticated/grupos.index'
import { Route as AuthenticatedGruposGroupIdRouteImport } from './routes/_authenticated/grupos.$groupId'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiOauthMercadopagoStartRouteImport } from './routes/api/oauth/mercadopago/start'
import { Route as ApiOauthMercadopagoCallbackRouteImport } from './routes/api/oauth/mercadopago/callback'
import { Route as AuthenticatedGruposGroupIdLinksRouteImport } from './routes/_authenticated/grupos.$groupId_.links'
import { Route as AuthenticatedGruposGroupIdConferenciaRouteImport } from './routes/_authenticated/grupos.$groupId_.conferencia'
import { Route as AuthenticatedGruposGroupIdCobrarRouteImport } from './routes/_authenticated/grupos.$groupId_.cobrar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarTokenRoute = PagarTokenRouteImport.update({
  id: '/pagar/$token',
  path: '/pagar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarTokenRoute = EntrarTokenRouteImport.update({
  id: '/entrar/$token',
  path: '/entrar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChargesRoute = ApiChargesRouteImport.update({
  id: '/api/charges',
  path: '/api/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasPeladasRoute =
  AuthenticatedMinhasPeladasRouteImport.update({
    id: '/minhas-peladas',
    path: '/minhas-peladas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasCobrancasRoute =
  AuthenticatedMinhasCobrancasRouteImport.update({
    id: '/minhas-cobrancas',
    path: '/minhas-cobrancas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposIndexRoute =
  AuthenticatedGruposIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGruposRoute,
  } as any)
const AuthenticatedGruposGroupIdRoute =
  AuthenticatedGruposGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGruposRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMercadopagoStartRoute =
  ApiOauthMercadopagoStartRouteImport.update({
    id: '/api/oauth/mercadopago/start',
    path: '/api/oauth/mercadopago/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMercadopagoCallbackRoute =
  ApiOauthMercadopagoCallbackRouteImport.update({
    id: '/api/oauth/mercadopago/callback',
    path: '/api/oauth/mercadopago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGruposGroupIdLinksRoute =
  AuthenticatedGruposGroupIdLinksRouteImport.update({
    id: '/$groupId_/links',
    path: '/$groupId/links',
    getParentRoute: () => AuthenticatedGruposRoute,
  } as any)
const AuthenticatedGruposGroupIdConferenciaRoute =
  AuthenticatedGruposGroupIdConferenciaRouteImport.update({
    id: '/$groupId_/conferencia',
    path: '/$groupId/conferencia',
    getParentRoute: () => AuthenticatedGruposRoute,
  } as any)
const AuthenticatedGruposGroupIdCobrarRoute =
  AuthenticatedGruposGroupIdCobrarRouteImport.update({
    id: '/$groupId_/cobrar',
    path: '/$groupId/cobrar',
    getParentRoute: () => AuthenticatedGruposRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/grupos': typeof AuthenticatedGruposRouteWithChildren
  '/minhas-cobrancas': typeof AuthenticatedMinhasCobrancasRoute
  '/minhas-peladas': typeof AuthenticatedMinhasPeladasRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/api/charges': typeof ApiChargesRoute
  '/entrar/$token': typeof EntrarTokenRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/grupos/$groupId': typeof AuthenticatedGruposGroupIdRoute
  '/grupos/': typeof AuthenticatedGruposIndexRoute
  '/grupos/$groupId/cobrar': typeof AuthenticatedGruposGroupIdCobrarRoute
  '/grupos/$groupId/conferencia': typeof AuthenticatedGruposGroupIdConferenciaRoute
  '/grupos/$groupId/links': typeof AuthenticatedGruposGroupIdLinksRoute
  '/api/oauth/mercadopago/callback': typeof ApiOauthMercadopagoCallbackRoute
  '/api/oauth/mercadopago/start': typeof ApiOauthMercadopagoStartRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minhas-cobrancas': typeof AuthenticatedMinhasCobrancasRoute
  '/minhas-peladas': typeof AuthenticatedMinhasPeladasRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/api/charges': typeof ApiChargesRoute
  '/entrar/$token': typeof EntrarTokenRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/grupos/$groupId': typeof AuthenticatedGruposGroupIdRoute
  '/grupos': typeof AuthenticatedGruposIndexRoute
  '/grupos/$groupId/cobrar': typeof AuthenticatedGruposGroupIdCobrarRoute
  '/grupos/$groupId/conferencia': typeof AuthenticatedGruposGroupIdConferenciaRoute
  '/grupos/$groupId/links': typeof AuthenticatedGruposGroupIdLinksRoute
  '/api/oauth/mercadopago/callback': typeof ApiOauthMercadopagoCallbackRoute
  '/api/oauth/mercadopago/start': typeof ApiOauthMercadopagoStartRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRouteWithChildren
  '/_authenticated/minhas-cobrancas': typeof AuthenticatedMinhasCobrancasRoute
  '/_authenticated/minhas-peladas': typeof AuthenticatedMinhasPeladasRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/api/charges': typeof ApiChargesRoute
  '/entrar/$token': typeof EntrarTokenRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/_authenticated/grupos/$groupId': typeof AuthenticatedGruposGroupIdRoute
  '/_authenticated/grupos/': typeof AuthenticatedGruposIndexRoute
  '/_authenticated/grupos/$groupId_/cobrar': typeof AuthenticatedGruposGroupIdCobrarRoute
  '/_authenticated/grupos/$groupId_/conferencia': typeof AuthenticatedGruposGroupIdConferenciaRoute
  '/_authenticated/grupos/$groupId_/links': typeof AuthenticatedGruposGroupIdLinksRoute
  '/api/oauth/mercadopago/callback': typeof ApiOauthMercadopagoCallbackRoute
  '/api/oauth/mercadopago/start': typeof ApiOauthMercadopagoStartRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/grupos'
    | '/minhas-cobrancas'
    | '/minhas-peladas'
    | '/pagamentos'
    | '/api/charges'
    | '/entrar/$token'
    | '/pagar/$token'
    | '/grupos/$groupId'
    | '/grupos/'
    | '/grupos/$groupId/cobrar'
    | '/grupos/$groupId/conferencia'
    | '/grupos/$groupId/links'
    | '/api/oauth/mercadopago/callback'
    | '/api/oauth/mercadopago/start'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/minhas-cobrancas'
    | '/minhas-peladas'
    | '/pagamentos'
    | '/api/charges'
    | '/entrar/$token'
    | '/pagar/$token'
    | '/grupos/$groupId'
    | '/grupos'
    | '/grupos/$groupId/cobrar'
    | '/grupos/$groupId/conferencia'
    | '/grupos/$groupId/links'
    | '/api/oauth/mercadopago/callback'
    | '/api/oauth/mercadopago/start'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/grupos'
    | '/_authenticated/minhas-cobrancas'
    | '/_authenticated/minhas-peladas'
    | '/_authenticated/pagamentos'
    | '/api/charges'
    | '/entrar/$token'
    | '/pagar/$token'
    | '/_authenticated/grupos/$groupId'
    | '/_authenticated/grupos/'
    | '/_authenticated/grupos/$groupId_/cobrar'
    | '/_authenticated/grupos/$groupId_/conferencia'
    | '/_authenticated/grupos/$groupId_/links'
    | '/api/oauth/mercadopago/callback'
    | '/api/oauth/mercadopago/start'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChargesRoute: typeof ApiChargesRoute
  EntrarTokenRoute: typeof EntrarTokenRoute
  PagarTokenRoute: typeof PagarTokenRoute
  ApiOauthMercadopagoCallbackRoute: typeof ApiOauthMercadopagoCallbackRoute
  ApiOauthMercadopagoStartRoute: typeof ApiOauthMercadopagoStartRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar/$token': {
      id: '/pagar/$token'
      path: '/pagar/$token'
      fullPath: '/pagar/$token'
      preLoaderRoute: typeof PagarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/$token': {
      id: '/entrar/$token'
      path: '/entrar/$token'
      fullPath: '/entrar/$token'
      preLoaderRoute: typeof EntrarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charges': {
      id: '/api/charges'
      path: '/api/charges'
      fullPath: '/api/charges'
      preLoaderRoute: typeof ApiChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-peladas': {
      id: '/_authenticated/minhas-peladas'
      path: '/minhas-peladas'
      fullPath: '/minhas-peladas'
      preLoaderRoute: typeof AuthenticatedMinhasPeladasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-cobrancas': {
      id: '/_authenticated/minhas-cobrancas'
      path: '/minhas-cobrancas'
      fullPath: '/minhas-cobrancas'
      preLoaderRoute: typeof AuthenticatedMinhasCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos/': {
      id: '/_authenticated/grupos/'
      path: '/'
      fullPath: '/grupos/'
      preLoaderRoute: typeof AuthenticatedGruposIndexRouteImport
      parentRoute: typeof AuthenticatedGruposRoute
    }
    '/_authenticated/grupos/$groupId': {
      id: '/_authenticated/grupos/$groupId'
      path: '/$groupId'
      fullPath: '/grupos/$groupId'
      preLoaderRoute: typeof AuthenticatedGruposGroupIdRouteImport
      parentRoute: typeof AuthenticatedGruposRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/mercadopago/start': {
      id: '/api/oauth/mercadopago/start'
      path: '/api/oauth/mercadopago/start'
      fullPath: '/api/oauth/mercadopago/start'
      preLoaderRoute: typeof ApiOauthMercadopagoStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/mercadopago/callback': {
      id: '/api/oauth/mercadopago/callback'
      path: '/api/oauth/mercadopago/callback'
      fullPath: '/api/oauth/mercadopago/callback'
      preLoaderRoute: typeof ApiOauthMercadopagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/grupos/$groupId_/links': {
      id: '/_authenticated/grupos/$groupId_/links'
      path: '/$groupId/links'
      fullPath: '/grupos/$groupId/links'
      preLoaderRoute: typeof AuthenticatedGruposGroupIdLinksRouteImport
      parentRoute: typeof AuthenticatedGruposRoute
    }
    '/_authenticated/grupos/$groupId_/conferencia': {
      id: '/_authenticated/grupos/$groupId_/conferencia'
      path: '/$groupId/conferencia'
      fullPath: '/grupos/$groupId/conferencia'
      preLoaderRoute: typeof AuthenticatedGruposGroupIdConferenciaRouteImport
      parentRoute: typeof AuthenticatedGruposRoute
    }
    '/_authenticated/grupos/$groupId_/cobrar': {
      id: '/_authenticated/grupos/$groupId_/cobrar'
      path: '/$groupId/cobrar'
      fullPath: '/grupos/$groupId/cobrar'
      preLoaderRoute: typeof AuthenticatedGruposGroupIdCobrarRouteImport
      parentRoute: typeof AuthenticatedGruposRoute
    }
  }
}

interface AuthenticatedGruposRouteChildren {
  AuthenticatedGruposGroupIdRoute: typeof AuthenticatedGruposGroupIdRoute
  AuthenticatedGruposIndexRoute: typeof AuthenticatedGruposIndexRoute
  AuthenticatedGruposGroupIdCobrarRoute: typeof AuthenticatedGruposGroupIdCobrarRoute
  AuthenticatedGruposGroupIdConferenciaRoute: typeof AuthenticatedGruposGroupIdConferenciaRoute
  AuthenticatedGruposGroupIdLinksRoute: typeof AuthenticatedGruposGroupIdLinksRoute
}

const AuthenticatedGruposRouteChildren: AuthenticatedGruposRouteChildren = {
  AuthenticatedGruposGroupIdRoute: AuthenticatedGruposGroupIdRoute,
  AuthenticatedGruposIndexRoute: AuthenticatedGruposIndexRoute,
  AuthenticatedGruposGroupIdCobrarRoute: AuthenticatedGruposGroupIdCobrarRoute,
  AuthenticatedGruposGroupIdConferenciaRoute:
    AuthenticatedGruposGroupIdConferenciaRoute,
  AuthenticatedGruposGroupIdLinksRoute: AuthenticatedGruposGroupIdLinksRoute,
}

const AuthenticatedGruposRouteWithChildren =
  AuthenticatedGruposRoute._addFileChildren(AuthenticatedGruposRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRouteWithChildren
  AuthenticatedMinhasCobrancasRoute: typeof AuthenticatedMinhasCobrancasRoute
  AuthenticatedMinhasPeladasRoute: typeof AuthenticatedMinhasPeladasRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGruposRoute: AuthenticatedGruposRouteWithChildren,
  AuthenticatedMinhasCobrancasRoute: AuthenticatedMinhasCobrancasRoute,
  AuthenticatedMinhasPeladasRoute: AuthenticatedMinhasPeladasRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChargesRoute: ApiChargesRoute,
  EntrarTokenRoute: EntrarTokenRoute,
  PagarTokenRoute: PagarTokenRoute,
  ApiOauthMercadopagoCallbackRoute: ApiOauthMercadopagoCallbackRoute,
  ApiOauthMercadopagoStartRoute: ApiOauthMercadopagoStartRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
